services:
  - type: worker
    name: smc-scanner-bot
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm install --legacy-peer-deps
    startCommand: node scanner/worker.mjs
    envVars:
      - key: TELEGRAM_TOKEN
        value: 7692139204:AAFalwvSeYMunaY_T_zUqQn3rSRWhzo-8N4
      - key: TELEGRAM_CHAT_ID
        value: "1068346212"
      - key: NODE_ENV
        value: production
